# Generated by Django 2.2.16 on 2020-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='findme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
